Special instructions for windows users in README
NASA-IMPACT/hls-foundation-os pull request #35
Opened 2023-10-26 23:06 UTC by agraham9966

Added some instructions based on how I got the package setup on my windows 10 machine. Haven't run into any other issues so far however - maybe one of the maintainers here can try it out for themselves before merging.

2023-11-06 08:45 UTC, CarlosGomes98 requested changes
Thanks for your contribution! I left some small comments, just encouraging the use of generic paths

2023-11-06 08:45 UTC, CarlosGomes98 commented on README.md
> +1. `conda create -n hlsdl python=3.9`
Can we change -n to generic <environment-name>?

2023-11-06 08:45 UTC, CarlosGomes98 commented on README.md
> +4. `git clone https://github.com/open-mmlab/mmsegmentation.git D:\your-local-dir\mmsegmentation`
Can we change the destination path to some generic names e.g. <mmseg_path> <hls-foundation-os_path>?

2023-11-06 08:45 UTC, CarlosGomes98 commented on README.md
> +5. `cd D:\mmsegmentation`
Can we change this to the same generic path as above?

2023-11-06 08:45 UTC, CarlosGomes98 commented on README.md
> +8. `cd D:\your-local-dir\hls-foundation-os`
Same as above

2023-11-06 08:45 UTC, CarlosGomes98 commented on README.md
> +7. modify setup.py so it installs from the cloned mmsegmentation. Change line `mmsegmentation @ git+https://github.com/open-mmlab/mmsegmentation.git@186572a3ce64ac9b6b37e66d58c76515000c3280` to `mmse
same as above

2023-11-07 00:25 UTC, agraham9966 commented
Thanks Carlos happy to help- just pushed those changes. Cheers!

2023-12-11 14:02 UTC, merged